version: "3.7"

services:

  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: user_me
      POSTGRES_PASSWORD: user_me
    volumes:
      - /var/lib/postgresql/data
    networks:
      - default
      - postgresql-net

  redis1:
    container_name: redis1
    image: redis:latest
    restart: always
    ports:
      - 6380:6380
    volumes:
      - /var/lib/redis1/data
    networks:
      - default
      - redis1-net

networks:
  postgresql-net:
    driver: bridge
  redis1-net:
    driver: bridge