
Server:
  host: localhost
  port: 8010

spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: none
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    first:
      url: jdbc:postgresql://3.35.195.160:5432/hooxi
      username: hooxi_user
      password: hooxi_user
      driver-class-name: org.postgresql.Driver
      hikari.connection-timeout: 60000
      hikari.maximum-pool-size: 10
    second:
      url: jdbc:postgresql://hooxiproduct.cyjcyduufdox.ap-northeast-2.rds.amazonaws.com/hooxiprod
      username: hooxiadmin
      password: hooxi_user
      driver-class-name: org.postgresql.Driver
      hikari.connection-timeout: 60000
      hikari.maximum-pool-size: 10


