

server:
  host: localhost
  port: 9000


swagger:
  url: /swagger-ui/index.html#
#PostGresql info
spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://ws.uinetworks.kr:54344/sparwk_local
    username: sparwk_local_user
    password: sparwk_local_user
#    url: jdbc:log4jdbc:postgresql://52.78.232.32:5432/sparwkdb
#    username: sparwk_usr01
#    password: sparwk_usr01
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    driver-class-name: org.postgresql.Driver
    hikari.connection-timeout: 60000
    hikari.maximum-pool-size: 2
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # Hibernate
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: none
        #ddl-auto: create
        #ddl-auto: create-drop
        #ddl-auto: update
        #        ddl-auto: validate
        show_sql: true
        format_sql: true
  #        sql: true
  #        use_sql_comments: true


  jackson:
    serialization:
      fail-on-empty-beans: false

  security:
    key: asdjk12iu89djakld192dnkasd192p3asdkl1229asjdkl12e9asdjkl1239asdjkl12398asdjkl123u89o0asdjkl12839
    oauth2:
      resourceserver:
        jwt:
          key-value: classpath:simple.pub
#          issuer-uri:
#          jwk-set-uri:
#          jws-algorithm:
#          public-key-location:
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace